export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_MENTORS_REQUEST = 'FETCH_MENTORS_REQUEST';
export const FETCH_MENTORS_SUCCESS = 'FETCH_MENTORS_SUCCESS';
export const FETCH_MENTORS_FAILURE = 'FETCH_MENTORS_FAILURE';

export const FETCH_MENTEES_REQUEST = 'FETCH_MENTEES_REQUEST';
export const FETCH_MENTEES_SUCCESS = 'FETCH_MENTEES_SUCCESS';
export const FETCH_MENTEES_FAILURE = 'FETCH_MENTEES_FAILURE';